export const dates = [
    {
        startDay: "Saturday",
        startDate: "1 Mar, 2025",
        endDay: "Monday",
        endDate: "7 Mar, 2025",
        anglerSpaces: 0,
    },
    {
        startDay: "Saturday",
        startDate: "8 Mar, 2025",
        endDay: "Monday",
        endDate: "14 Mar, 2025",
        anglerSpaces: 3,
    },
    {
        startDay: "Saturday",
        startDate: "15 Mar, 2025",
        endDay: "Monday",
        endDate: "21 Mar, 2025",
        anglerSpaces: 4,
    },
    {
        startDay: "Saturday",
        startDate: "22 Mar, 2025",
        endDay: "Monday",
        endDate: "28 Mar, 2025",
        anglerSpaces: 3,
    },
    {
        startDay: "Saturday",
        startDate: "29 Mar, 2025",
        endDay: "Monday",
        endDate: "4 April, 2025",
        anglerSpaces: 2,
    },
    {
        startDay: "Saturday",
        startDate: "5 April, 2025",
        endDay: "Monday",
        endDate: "10 April, 2025",
        anglerSpaces: 1,
    },
    {
        startDay: "Saturday",
        startDate: "11 April, 2025",
        endDay: "Monday",
        endDate: "16 April, 2025",
        anglerSpaces: 3,
    },
    {
        startDay: "Saturday",
        startDate: "17 April, 2025",
        endDay: "Monday",
        endDate: "21 April, 2025",
        anglerSpaces: 5,
    },
]
