import {
  tents,
  meals,
  shop,
  scene,
  custom,
  guide,
  tent1,
  tent2,
  tent3,
  meal1,
  meal2,
  meal3,
  shop1,
  shop2,
  shop3,
  scene1,
  scene2,
  scene3,
  guide1,
  guide2,
  guide3,
} from "../../assets/index";

export const UspData = [
  {
    icon: tents,
    title: "Luxury Tents",
    desc: "Experience the thrill of the outdoors without sacrificing comfort. Our deluxe Swiss tents boast amenities like comfortable wooden beds, side tables, electric connections, fans, and even desert coolers to keep you cool during warmer months.",
    img1: tent1,
    img2: tent2,
    img3: tent3,
  },
  {
    icon: custom,
    title: "Customize Your Itinerary",
    desc: "Don't settle for a pre-set itinerary! We offer the flexibility to design your ideal fishing adventure. Choose from various itineraries and personalize them further by adding exciting optional activities that match your interests.",
  },
  {
    icon: meals,
    title: "Freshly Prepared Meals",
    desc: "Indulge in delicious, hygienically prepared meals tailored to your preferences. Savour each bite while surrounded by the breathtaking natural beauty of the Himalayas.",
    img1: meal1,
    img2: meal2,
    img3: meal3,
  },
  {
    icon: shop,
    title: "One-Stop Shop for Fishing Needs",
    desc: "Focus on catching trophy fish, not logistics or hotels. We provide replacement lures and terminal tackle right at the camp, ensuring you have everything you need for a successful fishing trip.",
    img1: shop1,
    img2: shop2,
    img3: shop3,
  },
  {
    icon: scene,
    title: "Unwind in a Serene Location",
    desc: "Wake up to the invigorating sounds of the rushing Maha Kali River and the melodious chirping of birds. Our camp's idyllic setting provides the perfect view of the famous confluence of Sarayu and Kali rivers.",
    img1: scene1,
    img2: scene2,
    img3: scene3,
  },
  {
    icon: guide,
    title: "Camp Owner as Your Guide",
    desc: "Our dedicated camp owner, Daniel Abraham, isn't just your host – he's also a seasoned fishing guide. Benefit from his extensive knowledge and passion for the sport as he leads you to the prime fishing spots on the river.",
    img1: guide1,
    img2: guide2,
    img3: guide3,
  },
];
